<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <StartupObject>TasaPlusDesktop.Program</StartupObject>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <ApplicationIcon>logo.ico</ApplicationIcon>
    <AssemblyName>TasaPlus-Setup</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TasaPlus.Shared\TasaPlus.Shared.csproj" />
  </ItemGroup>

</Project>
